# Generated by Django 3.2.7 on 2021-09-30 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itelapp', '0002_auto_20210928_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(default='cat.jpg', upload_to='category')),
                ('min_quant', models.IntegerField()),
                ('max_quant', models.IntegerField()),
                ('latest', models.BooleanField()),
                ('available', models.BooleanField()),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itelapp.category')),
            ],
        ),
    ]
