# Generated by Django 3.2.7 on 2021-09-30 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itelapp', '0004_product_best_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='best_seller',
            field=models.BooleanField(default=False),
        ),
    ]
