# Generated by Django 3.2.7 on 2021-09-30 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itelapp', '0005_alter_product_best_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='category',
        ),
    ]
